### ISSUE TITLE
Host directly on github pages?

### ISSUE THREAD

**Issue by waldyrious** [BryanBarrera/copy-html#1]
By using the gh-pages branch instead of master, the live demo would automatically be hosted in https://BryanBarrera.github.io/copy-html, and stay in sync with the repo -- no need to host a copy elsewhere and sync changes. What do you think?

**Comment by BryanBarrera** [comment]
Not sure how to do that.. @waldyrious

**Comment by waldyrious** [comment]
You should be able to create a new branch called "gh-pages" from the main repository page (in the Branch: master dropdown); that alone will make the page instantly available through the Github Pages infrastructure, in the link I pointed above :)

Then, to complete the move, you should go to https://github.com/BryanBarrera/copy-html/branches and click the "change default branch" button to set gh-pages as the default branch, then go back to the branches list and delete the master branch. The previous git history of commits on master is preserved, so there's nothing to lose :) Let me know if this helps.

**Comment by BryanBarrera** [comment]
Thanks man I will give that a try @waldyrious

**Comment by BryanBarrera** [comment]
Thanks man - http://bryanbarrera.github.io/copy-html/ @waldyrious

**Comment by waldyrious** [comment]
It seems as if the gh-pages branch was created from scratch (not sure why -- did you create it in the command line or using the github web interface?), and is not connected to the master branch (see https://github.com/BryanBarrera/copy-html/network, and the repo page which says "2 commits" above the colored bar). That means you can't delete the master branch or you'd lose the commit history and gradual evolution of this project.

If you'd like I can fix this up for you. Just give me temporary commit access to this repo and I'll set it up so history is propery preserved. Let me know :)

**Comment by waldyrious** [comment]
@BryanBarrera please let me know if you're not interested at all, or if it's just a matter of reduced availability :)
